version: '3.8'

services:
  unhash-service:
    build:
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
  backend:
    driver: bridge